name: Deploy

on:
  push:
    branches:
      - master

jobs:
  all:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
        with:
          args: deploy --remote-only
